import {Roboto} from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import {Providers} from "@/components/Providers";
const roboto = Roboto({
	subsets: ["cyrillic"],
	weight: ["100", "400", "500"],
});

export const metadata = {
	title: "Билетопоиск",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<Providers>
					<Header />
					<main>{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
